---
title: "Increased spatial range and abundance of greater weaver (*Trachinus draco*)"
author: "Max Lindmark"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: 
  html:
    embed-resources: true
    fig-width: 8
    toc: true
    #fig-asp: 0.618
knitr: 
  opts_chunk:
    fig.align: center
editor: source
execute: 
  echo: true
  eval: true
  cache: false
---

```{r}
#| warning: false
#| message: false

library(tidyr)
library(dplyr)
library(ggplot2); theme_set(theme_light())
library(sdmTMB)
library(RCurl)
```

### Introduction
Here I show an example data set (greater weaver, *Trachinus draco*, from the west coast) we could use to test for power to detect time series chance.

### Read and prepare data
We prepare it like this to be able to fit a geostatistical model which we use to estimate a relative biomass index (<https://fiskbarometern.se/rapport/2024/species/Fj%C3%A4rsing>).

```{r}
#| warning: false
#| message: false

d <- read.csv(
  "https://github.com/maxlindmark/greater-weever/raw/refs/heads/main/data/Trawl%20Surveys%20Zincl%20(L).csv",
  sep = ";", dec = ",") |> 
  janitor::clean_names() |> 
  filter(subdiv <= 21) |>  
  filter(validity == "V") |> 
  mutate(haul_id = paste(year, quarter, month, haul)) |> 
  mutate(median_swept = median(swept_area, na.rm = TRUE), .by = year) |>
  mutate(swept_area = ifelse(is.na(swept_area), median_swept, swept_area),
         kg_hour = replace_na(kg_hour, 0),
         kg = kg_hour * (duration / 60),
         density = kg / swept_area) |> 
  distinct(haul_id, .keep_all = TRUE) |> 
  filter(density < quantile(density, probs = 0.999)) |> 
  dplyr::select(date, year, quarter, month, subdiv, lat, long, density) |> 
  mutate(lat = floor(lat/100)+(lat-100*floor(lat/100))/60,
         lon = floor(long/100)+(long-100*floor(long/100))/60,
         lat = ifelse(lat<0,-1*lat,lat),
         lon = ifelse(long<0,-1*lon,lon)) |> 
  add_utm_columns(ll_names = c("lon", "lat"))
```

```{r}
glimpse(d)
```

### Visualize
Plot a naive mean biomass density in quater 1

```{r}
d |> 
  filter(quarter == 3) |> 
  summarise(density = mean(density), .by = year) |> 
  ggplot(aes(year, density)) + 
  geom_point(size = 1.5) + 
  geom_line() +
  labs(x = "Year", y = "Biomass Density")
```

